---
title: "Penguin Scatter Plot"
author: "Annika Gonzales"
date: "7/15/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install tidyverse
install.packages("dplyr")
library(tidyverse)
#install remotes
install.packages(remotes)
#install data
remotes::install_github("allisonhorst/palmerpenguins")
library(palmerpenguins)
penguins
#check data import
library(palmerpenguins)
penguins
#double check data import
glimpse(penguins)
#exploring import
unique(penguins$species)
unique(penguins$island)
#scatterplot data viz
ggplot(data = penguins,
aes(x = bill_length_mm, y = bill_depth_mm)) +
geom_point(aes(color = species, shape = species),
size = 3, alpha = 0.8) +
#theme_minimal() +
scale_color_manual(values = c("darkorange", "purple", "cyan4")) +
labs(title = "Penguin size, Palmer Station LTER",
subtitle = "Bill Depth and Bill Length for Adelie, Chinstrap, and Gentoo Penguins",
x = "Bill Length (mm)",
y = "Bill Depth  (mm)",
color = "Penguin species",
shape = "Penguin species") +
theme_minimal()
```


```{r prompt 1}
#Prompt 1
class(penguins$bill_length_mm)
class(penguins$flipper_length_mm)
class(penguins$sex)
class(penguins$body_mass_g)
class(penguins$species)
class(penguins$island)
class(penguins$bill_depth_mm)

levels(penguins$bill_length_mm)
levels(penguins$flipper_length_mm)
levels(penguins$sex)
levels(penguins$body_mass_g)
levels(penguins$species)
levels(penguins$island)
levels(penguins$bill_depth_mm)

```

```{r prompt 2}
#Bar graph counts > colorblind palettes
penguins %>%
  count(species) %>%
  ggplot() + geom_col(aes(x = species, y = n,fill = species)) + geom_label(aes(x= species, y= n, label =n)) + scale_fill_manual(values=c("#009E73" , "#CC79A7" , "gray")) + theme_minimal() +labs(title= 'Penguins Species Count')
```


```{r prompt 3}
summary(penguins$species)
summary(penguins$bill_length_mm)
summary (penguins$body_mass_g)
```




















